### PR TITLE
Implementation of the workflow

### PR DESCRIPTION
**Pull request by celprov**
Closes #

This PR implements the workflow.

## Proposed Changes

  - Implement a parser (strongly inspired by the parser of phys2denoise)
  - Add an interface to iteratively generates the figures
  - Add an interface to compute the metrics iteratively
  - Add an interface to save the metrics as a json or csv
  - Adapt the documentation to the reality that certain metrics function can take as input a peakdet Physio object or a np.array
  - Remove smoothness as its implementation is not working

!! The generation of the visual report is missing in the workflow and needs to be added !!

## Change Type

- [ ] `bugfix` (+0.0.1)
- [x] `minor` (+0.1.0)
- [ ] `major`  (+1.0.0)
- [ ] `refactoring` (no version update)
- [ ] `test` (no version update)
- [ ] `infrastructure` (no version update)
- [ ] `documentation` (no version update)
- [ ] `other`

### CODE REVIEW

**Comment by SRSteinkamp** [comment]
Same...
The only thing I have to go by is the GoogleDoc you shared for physioQC and Celine's implementation (which is not working as intended) ... so I am also not sure what smoothness is here and had hoped you had some insight :) ... also happy to remove the measure for now until we have a better grasp of it.

**Comment by celprov** [comment]
@SRSteinkamp MRIQC computes the smoothness of the fMRI image as Full-width half maximum smoothness (fwhm*)
Here is the info I've found in MRIQC code about how it is implemented

> **fwhm** (*nipype interface to AFNI*): The :abbr:`FWHM (full-width half maximum)` of
>   the spatial distribution of the image intensity values in units of voxels [Forman1995]_.
>   Lower values are better, higher values indicate a blurrier image. Uses the gaussian
>   width estimator filter implemented in AFNI's ``3dFWHMx``:
> 
>   .. math ::
> 
>       \text{FWHM} = \sqrt{-{\left[4 \ln{(1-\frac{\sigma^2_{X^m_{i+1,j}-X^m_{i,j}}}
>       {2\sigma^2_{X^m_{i,j}}}})\right]}^{-1}}

Here is the visual representation of the equation
image

**Comment by SRSteinkamp** [comment]
Will have a look if it fits for 1D time series signals (and not images) @celprov :) 

@smoia ... before this PR is ready for review, we need to review and merge #5 first. This PR already references the visualizations we implemented.

**Comment by celprov** [comment]
In the project wrap-up, we proposed to separate the smoothness from this PR, so that the rest of the content can already be reviewed and merged and to work on the development of the smoothness in another PR.

**Comment by celprov** [comment]
@m-miedema I think this PR is ready for review (unless @SRSteinkamp says otherwise).

**Comment by m-miedema** [comment]
This is a really exciting PR! I know @SRSteinkamp still wants to work on some visualizations but I thought I'd go ahead and take a look in the meantime. However, I can't get the CLI to run. I'm on Windows (I know this is new ground) and after installing with pip, and running `physioqc -h` I receive the following error:
```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code 
  File "C:\Users\data_acq\AppData\Local\Programs\Python\Python311\Scripts\physioqc.exe\__main__.py", line 4, in <module>
  File "C:\Users\data_acq\AppData\Local\Programs\Python\Python311\Lib\site-packages\physioqc\workflow.py", line 10, in <module>
    from .cli.run import _get_parser
ModuleNotFoundError: No module named 'physioqc.cli'
```
I haven't figured out how to solve this myself, although @me-pic has replicated the error running on a Mac.

**Comment by m-miedema** [comment]
It seems like there were some __init__ files missing! After that, it seems like the main thing is to add in the visualizations. @SRSteinkamp let me know if you need any help :)

**Comment by smoia** [comment]
@m-miedema or @me-pic can you push the missing __init__ to this branch?

**Comment by celprov** [comment]
If the workflow works as such, I would merge this PR and work on adding new visualizations in another PR.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by m-miedema** [comment]
@celprov I haven't been able to fully test it yet, as the workflow file was raising errors where the visualizations are missing.

**Comment by celprov** [comment]
Is it a matter that the visualizations missing are implemented in PR #5 ?

**Comment by m-miedema** [comment]
I'm not quite sure -- from what I can tell, the visualizations have inconsistent naming conventions across the two branches, but it seems like from @SRSteinkamp's comment above, it will not be too difficult to implement once that PR has been merged.

**Review by goodalse2019 — APPROVED** [review]
Looks good from my end!

**Review by goodalse2019 — APPROVED** [review]
Try 2, looks good

**Review by goodalse2019 — APPROVED** [review]
yes!

**Review by goodalse2019 — APPROVED** [review]
I officially viewed!

**Review by goodalse2019 — APPROVED** [review]
looks good!

**Pull request merged**
