### PR TITLE
Update .zenodo.json file to include multiple affiliations 

### PR DESCRIPTION
**Pull request by RayStick**
Closes #

Update .zeondo.json file to include multiple affiliations
As discussed on slack with @smoia 

## Proposed Changes

  - Rachael and Stefano now have multiple affiliations listed 

## Change Type

- [ ] `bugfix` (+0.0.1)
- [ ] `minor` (+0.1.0)
- [ ] `major`  (+1.0.0)
- [ ] `refactoring` (no version update)
- [ ] `test` (no version update)
- [x] `infrastructure` (no version update)
- [x] `documentation` (no version update)
- [ ] `other`

## Checklist before review

- [x] I added everything I wanted to add to this PR.
- [ ] \[Code or tests only\] I wrote/updated the necessary docstrings.
- [ ] \[Code or tests only\] I ran and passed tests locally.
- [ ] \[Documentation only\] I built the docs locally.
- [x] My contribution is harmonious with the rest of the code: I'm not introducing repetitions.
- [x] My code respects the adopted style, especially linting conventions.
- [x] The title of this PR is explanatory on its own, enough to be understood as part of a changelog.
- [x] I added or indicated the right labels.

- [ ] I added information regarding the timeline of completion for this PR.

- [x] Please, comment on my PR while it's a draft and give me feedback on the development!

### CODE REVIEW

**Comment by smoia** [comment]
I guess it's correct, thank you @RayStick !
Unfortunately we can't really test until the next version trigger. Let's see what happens then!

**Comment by RayStick** [comment]
Ah I see! 
Shall I go ahead and update the other repos anyway? (with out multiple affiliations)

**Comment by RayStick** [comment]
@smoia this seems to have worked 🥳 yeah?
https://zenodo.org/records/13356552
Shall I implement the same multiple affiliations (for you and me) for other repos?

**Comment by smoia** [comment]
Unfortunately it didn't - we're already at release 0.8.1 but Zenodo is not keeping up. I wrote to them to ask why, but with no avail.

Do you want to try to contact them again? that'd help. Alternatively, I saw that they are now working with CFF files, if you want to give it a try?

**Comment by RayStick** [comment]
Ohhhh I did not look closely enough. I see now 😭

**Pull request merged**
